version: "3.8"

services:

  product-demo:
    container_name: "product-demo"
    build:
      context: .  # Path to the directory containing the Dockerfile for Product_Demo
      dockerfile: /Product-Demo/Dockerfile
    ports:
      - "5000:80"
    

  orders-demo:
    container_name: "orders-demo"
    build:
      context: .  # Path to the directory containing the Dockerfile for Orders_Demo
      dockerfile: /Orders_Demo/Dockerfile
    ports:
      - "4000:80"
  

  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local